### ISSUE TITLE
Facebook Ads Extension Not Working

### ISSUE THREAD

**Issue by aravindlikes** [facebookincubator/Facebook-For-OpenCart#122]
Installed new version  2.1.5 ads extension. But getting Error
"There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing."

In the console, I got the error 
"GET https://www.sundarisilks.com/admin/index.php?route=extension/facebookadsextension/getinitialproductsyncstatus&user_token=Xjai213ihQygdNXyUB5JpnMUClpoEaL5&token=Xjai213ihQygdNXyUB5JpnMUClpoEaL5 400"

![image](https://user-images.githubusercontent.com/17896446/54372550-88c80680-46a1-11e9-94b6-3d62ed8d0c5d.png)

![image](https://user-images.githubusercontent.com/17896446/54372638-b6ad4b00-46a1-11e9-90bd-fd2e9aec7967.png)

**Comment by Emwestside** [comment]
You can adjust the number on this file on your webserver, after you installed the plugin.
https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/system/library/facebookcommonutils.php#L113

**Comment by aravindlikes** [comment]
It's already 100 in my file also

![image](https://user-images.githubusercontent.com/17896446/54415030-18f96080-4721-11e9-866a-3210ed9f7474.png)

**Comment by aravindlikes** [comment]
It's already 100 in my file server
But still getting error

![image](https://user-images.githubusercontent.com/17896446/54415085-3dedd380-4721-11e9-89ac-9904ded7ea1e.png)

**Comment by Emwestside** [comment]
Change it to 1000

**Comment by aravindlikes** [comment]
Changed It to 1000 

Still Getting Error

The error in the console

![image](https://user-images.githubusercontent.com/17896446/54418166-1f400a80-472a-11e9-9df3-1f3f1803a55e.png)

**Comment by shue249** [comment]
@aravindlikes This error should have been resolved. We will close out this ticket, but pls reach out to us if you have any questions.

**Comment by aravindlikes** [comment]
@shue249 The error is still not resolved even after Changing "FACEBOOK_PRODUCT_QUERY_BATCH_COUNT = 1000" 

https://www.sundarisilks.com/admin/index.php?route=extension/facebookadsextension/getinitialproductsyncstatus&user_token=8OXl9KWiFGP0dZLK9hQVwkLyrnsKHczj&token=8OXl9KWiFGP0dZLK9hQVwkLyrnsKHczj This page getting 400 error.

![image](https://user-images.githubusercontent.com/17896446/54584576-bfa17200-4a3d-11e9-9be7-198bf3b4e212.png)

**Comment by shue249** [comment]
@aravindlikes Can you check your apache error logs to see if there's any error messages reflected there.

**Comment by aravindlikes** [comment]
@shue249 I have uninstalled facebook ads extension. I have developed my own RSS feed for products. In the catalog manager, I have added it as a data feed URL.
