### ISSUE TITLE
Tracking all new cases where access token shows as invalid

### ISSUE THREAD

**Issue by shue249** [facebookincubator/Facebook-For-OpenCart#158]
Reference to previous tickets:
https://github.com/facebookincubator/Facebook-For-OpenCart/issues/144

**What have been done:**
1. Fixed the issue with access token encountering "manage_pages permission is missing"
2. Release version 2.1.7 which shows out the detailed error message with the access token

**What do you need to do:**
1. Update your plugin to version 2.1.7 - https://github.com/facebookincubator/Facebook-For-OpenCart/releases/tag/v2.1.7

2. If your OpenCart admin panel is showing up an error message showing "invalid access token", do these steps to renew the access token.
![image](https://user-images.githubusercontent.com/11957585/53614459-06f1cb00-3c15-11e9-825b-c042eb15cebb.png)

3. If your OpenCart admin panel is showing up an error message showing "error", do these steps to delete away the existing settings and re-do the settings.
https://drive.google.com/open?id=1PenBy_xizQGszdiS5BrmVFPypn5HKnkL

**What happens if the access token is still invalid** 
1. If the error message still shows up as invalid access token due to expired session, check to see if you have logged out of Facebook on the browser. There is a known issue where the access token session becomes invalid if you log out of Facebook. Please comment below and share with us the use case for you logging out of Facebook.

2. If the error message still shows up, pls comment below and share with us a screenshot of the error message.
![image](https://user-images.githubusercontent.com/11957585/57190151-f712a200-6f49-11e9-9854-d77f0e18c8b7.png)

**Comment by svremeto** [comment]
Hello! I have exactly this problem:

There is an error making API calls using the access token. The error encountered is "The access token could not be decrypted".
To update your access token, please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.

**Comment by shue249** [comment]
@svremeto Can you pull out the Javascript console to inspect if there are any errors. If there are, can you force a reload of your browser.
![image](https://user-images.githubusercontent.com/11957585/57265687-67850480-70ab-11e9-94f5-e6527f1df7ee.png)

![image](https://user-images.githubusercontent.com/11957585/57265732-8f746800-70ab-11e9-9ecf-b0baac3cd323.png)

**Comment by shue249** [comment]
Logged out of FB - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/159

**Comment by svremeto** [comment]
Hello! I hope this is what you are looking for.
![facebook 4](https://user-images.githubusercontent.com/50319977/57282793-71f8cb80-70b6-11e9-9254-f982d8084bef.jpg)
When i clicked to Empty Cache and Hard Reload i received one more error, after click on the Menage Settings button i received one more error (its show by the arrow, and after clicking to the cookies button i received one more.

**Comment by svremeto** [comment]
Hello shue249, Did you found something? Could you help me, please?

**Comment by shue249** [comment]
@svremeto 2 things.

1. We have released a new version of the plugin 2.1.8. You need to empty your browser cache and force refresh again.

2. We suspect that the latest plugin files are not copied over to your webserver correctly. Can you ensure that the opencart folder as write access. In particular, you need to check if this file is updated correctly as from the error message on the console, the file is an old version.

https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/controller/extension/facebookadsextension.php

**Comment by svremeto** [comment]
I`ve checked the folder where the website is based and these are the settings http://prntscr.com/nmvdlm
Is it fine?

**Comment by svremeto** [comment]
I`ve installed the new plugin. I`ve copied the file that you send me and placed on my server. I`ve clicked the button "Empty Cache and Hard Reload" but still facing the same error...

**Comment by shue249** [comment]
@svremeto 
![image](https://user-images.githubusercontent.com/11957585/57564850-c87f4600-73e5-11e9-9277-d31b5271cb19.png)

![image](https://user-images.githubusercontent.com/11957585/57564877-26ac2900-73e6-11e9-8d37-4334500a70b8.png)

**Comment by svremeto** [comment]
Hello, i`ve tried to do this but i`m facing the same problem. Here is the file after reinstalling the plugin.

[facebookadsextension.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3168991/facebookadsextension.zip)

**Comment by saharock2019** [comment]
Hi 

i installed the new version of the extention and i get this error in my dashboard 
![1](https://user-images.githubusercontent.com/50554932/57586512-7114cf00-74e6-11e9-8649-a0660a3b211f.png)

when i get in the extention i got this

![2](https://user-images.githubusercontent.com/50554932/57586516-825ddb80-74e6-11e9-9f98-bf14f3acdda2.png)

so i tried to delete settings and i get this error
![3](https://user-images.githubusercontent.com/50554932/57586523-973a6f00-74e6-11e9-931b-7e876660806b.png)

and here is the log errors 

2019-05-12 2:54:10 - Error when querying FB page - The access token could not be decrypted
2019-05-12 2:54:10 - Error with getting the initial product sync status There is an error making API calls using the access token. The error encountered is "The access token could not be decrypted".<br/>To update your access token, please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
2019-05-12 13:21:12 - Get Sample product feed
2019-05-12 13:21:13 - Complete - Get Sample product feed
2019-05-12 13:21:18 - Error when querying FB page - The access token could not be decrypted
2019-05-12 13:21:18 - Error with getting the initial product sync status There is an error making API calls using the access token. The error encountered is "The access token could not be decrypted".<br/>To update your access token, please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
2019-05-12 17:55:05 - Error when querying FB page - The access token could not be decrypted
2019-05-12 18:11:48 - Sync for product 322
2019-05-12 18:11:49 - Error when querying FB page - The access token could not be decrypted
2019-05-12 18:11:50 - Error when querying FB page - The access token could not be decrypted
2019-05-12 18:27:20 - Error when querying FB page - The access token could not be decrypted
2019-05-12 18:29:53 - Get Sample product feed
2019-05-12 18:29:53 - Complete - Get Sample product feed
2019-05-12 18:29:59 - Error when querying FB page - The access token could not be decrypted
2019-05-12 18:29:59 - Error with getting the initial product sync status There is an error making API calls using the access token. The error encountered is "The access token could not be decrypted".<br/>To update your access token, please click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Update token.
2019-05-12 18:47:31 - Error when querying FB page - The access token could not be decrypted
2019-05-12 18:49:04 - Facebook Ads Extension version = 2.1.8
2019-05-12 18:49:04 - OpenCart version = 3.0.2.0
2019-05-12 18:49:04 - PHP version = 7.1.1
2019-05-12 18:49:04 - Verifying Availability of Facebook Ads Extension Settings Availability
2019-05-12 18:49:04 - FAE Setting ID = true
2019-05-12 18:49:04 - Pixel ID = true
2019-05-12 18:49:04 - Pixel use PII = true
2019-05-12 18:49:04 - Catalog ID = true
2019-05-12 18:49:04 - Page ID = true
2019-05-12 18:49:04 - Page Token = true
2019-05-12 18:49:04 - Feed ID = true
2019-05-12 18:49:04 - Upload ID = true
2019-05-12 18:49:04 - Upload end time = true
2019-05-12 18:49:04 - Messenger plugin = false
2019-05-12 18:49:04 - Messenger plugin, greeting text code customization = false
2019-05-12 18:49:04 - Messenger plugin, locale customization = false
2019-05-12 18:49:04 - Messenger plugin, theme color code customization = false

**Comment by shue249** [comment]
@saharock2019 
1. Can you enable the jaavscript console panel and share with us if there's any error messages shown on the console panel. This will help us to troubleshoot the screenshot which shows "Not found" error.

2. There is another workaround to display the option to refresh the access token. The steps are highlighted on this comment - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/142#issuecomment-482908951

**Comment by saharock2019** [comment]
Now the error is 
Failed to load resource: the server responded with a status of 400 (Bad Request)
dia.js:91 Bad Request
Bad Request
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>

2- the  dashboard shows : There is an error with Facebook Ads Extension setup. Click on Facebook Ads Extension, Manage Settings, go to Advanced options and click on Delete Settings to restart the setup.
Please contact Facebook via our Github if this error keeps showing.

still unable to delete settings  following error shows
![4](https://user-images.githubusercontent.com/50554932/57590734-38441c80-751d-11e9-9f07-6908f3bfde9b.png)
thank you for following

**Comment by shue249** [comment]
@saharock2019 How about this approach - https://github.com/facebookincubator/Facebook-For-OpenCart/issues/142#issuecomment-482908951? Are you able to see the option to update the access token?

We are looking into the issue of unable to delete the settings, in the meantime, pls do not try to delete away your settings.

**Comment by saharock2019** [comment]
How about this approach - #142 (comment)? Are you able to see the option to update the access token?
yes it worked fine

thank you for working on that issue. i need to delete settings because i have a new facebook page that i want to direct products to

best regards

**Comment by shue249** [comment]
@saharock2019 Thank you for your feedback. We are working to resolve the problem of not being able to delete away the settings. We will update you soonest once we have resolved the issue.

**Comment by shue249** [comment]
@svremeto Thanks for your file. We checked and found the file is correct. We have 1 more idea on where the problem is. Could you identify this file on your webserver and share with us?

![image](https://user-images.githubusercontent.com/11957585/57606445-7849e480-759b-11e9-8331-bf405a1aa527.png)

**Comment by svremeto** [comment]
@shue249 Here is the file
[dia.zip](https://github.com/facebookincubator/Facebook-For-OpenCart/files/3171895/dia.zip)

**Comment by saharock2019** [comment]
Hi
for the problem of deleting the setting here is the screenshot of error 
![5](https://user-images.githubusercontent.com/50554932/57699350-134bc880-7647-11e9-9fa0-3840657dcad6.jpg)

and i still have a bad request issue and the pixel is not firing
thank you for your help

**Comment by shue249** [comment]
@saharock2019 Thank you for your feedback and sharing the screenshots. We are actively working on this and checking this failure on our side. We will get back to you soonest once we have any updates!

**Comment by shue249** [comment]
@svremeto We checked the files and found that the files are correct. Currently, we are unsure what could be the problem(s) since you have already cleared cache and force reload the browser.

One more suggestion. Are you able to try to do the setup using a different browser? Eg firefox.

**Comment by svremeto** [comment]
I`ve tried and I succeed to open the Manage Settings button. I see some error here: http://prntscr.com/norhzd
I`ve typed my user name and password (I`m using this Facebook extension for the first time on this website) and i saw this: http://prntscr.com/norj4f and after closing the window and clicking Manage Settings button again i`m seeing the same error: http://prntscr.com/norj4f

**Comment by saharock2019** [comment]
@shue249 Still same problem. nothing changed in my side

**Comment by svremeto** [comment]
@shue249 I dont have such problem to delete away the settings. Just cant log in to facebook from the extension`s windows. https://prnt.sc/norj4f

**Comment by claudineythomazette** [comment]
> @shue249 I dont have such problem to delete away the settings. Just cant log in to facebook from the extension`s windows. https://prnt.sc/norj4f

the same for me...

**Comment by shue249** [comment]
@svremeto , @saharock2019 , @claudineythomazette 

Again, we apologise for the inconvenience and sub-optimal experience. We are doing the best to figure out the problem. Can we request for you to share a video recording of what you are experiencing so that we can better understand where could the errors be. Thanks in advance.

**Comment by shue249** [comment]
Possible duplicate error that @svremeto , @saharock2019  @claudineythomazette is facing https://github.com/facebookincubator/Facebook-For-OpenCart/issues/177

**Comment by svremeto** [comment]
This is the record https://drive.google.com/file/d/1Nb5Fek6uLzC-1KZRdPj10bvGyB4QUcPc/view

**Comment by shue249** [comment]
@svremeto , @saharock2019 , @claudineythomazette Can we ask for you to reach to us via email at ads_extension_opencart@fb.com. There is something we like to discuss with you offline. Pls also indicate your github user name so that it is easier for us to make the connection.

**Comment by shue249** [comment]
@svremeto , @saharock2019 , @claudineythomazette Thank you for your speedy response. We have landed a fix for your issue. Can you try to launch Facebook Ads Extension again and see if it is now working properly.

**Comment by saharock2019** [comment]
@shue249 nothing in my side. The page says we are workibg to fix this problem

**Comment by claudineythomazette** [comment]
> @shue249 nothing in my side. The page says we are workibg to fix this problem

same msg for me...

**Comment by svremeto** [comment]
Same

**Comment by VitaliiFesh** [comment]
@shue249 I'm not able to install extension since 2.1.6 and 2.1.7
Invalid file type!

What could be a reason?
Thank you!

**Comment by shue249** [comment]
@svremeto , @saharock2019 , @claudineythomazette 

Thank you for your patience with us. We are working to resolve this problem and we have some information and updates for you.

**Information**
Facebook Ads Extension/Facebook Business extension (the pop up window) and the Facebook for OpenCart (this plugin) is developed by Facebook. I am also an employee of Facebook and I am part of the core team which developed this solution (popup + plugin). I hope this helps to clarify on the ownership of the solution.

**Update**
1. We have rolled out some fixes that helps to solve some of the issues. And we will need your help to help us verify if these fixes are working for you. Because some of you have encounter the same problem but is due to different root causes (and may require different fixes).

2. To do the verification, pls follow the below steps:

  a. Install the version 2.1.8 of our Facebook for OpenCart plugin.

  b. Access the Facebook Ads Extension module using Chrome/Firefox browser. Ensure that you are able to see the Manage Settings button. If you cannot see the button but is stuck at "Checking on Upload status" message, please do a "Empty cache and hard reload" (pls wait for 5 seconds to see if the message goes off).
![image](https://user-images.githubusercontent.com/11957585/58371997-9de6ce80-7f49-11e9-80a6-4c5f9668b1bb.png)

  c. Click on the Manage Settings button. Verify if the Facebook Ads Extension loads properly.

  d. Access the Advanced options -> Delete Settings.

  e. Verify if the "Delete Settings" work.

3. Feedback to us by commenting on this thread if the steps work for you or if you failed at any of the steps. If you are failing at the steps, pls let us know which is the below step you are failing.

  a. Unable to see the Manage Settings button, even though I have Empty cache and hard reload

  b. Unable to see Facebook Ads Extension. It is showing up as "Sorry, something has gone wrong" error messages.

  c. Unable to delete the settings. It is showing up as "Sorry, something went wrong"

4. Depending on your error message, we will feedback to you accordingly.

Again, thank you for your patience and we really want to help you be successful by resolving these problems altogether.

**Comment by shue249** [comment]
@VitaliiFesh Are you using the exact zip file of our plugin or did you re-zip and renamed the file yourself. The plugin MUST end with ".ocmod.zip" extension, otherwise OpenCart will complain "Invalid file type"

**Comment by svremeto** [comment]
When I go to step "C" and click to Manage Settings i see this window http://prntscr.com/ntg16g as before.

b. Unable to see Facebook Ads Extension. It is showing up as "Sorry, something has gone wrong" error messages.

**Comment by svremeto** [comment]
@shue249 I`m still facing the same issue http://prntscr.com/nud2i8

**Comment by shue249** [comment]
@claudineythomazette Can you try to delete the settings away and see if it works.

**Comment by claudineythomazette** [comment]
@shue249 working for me!

But in the deletion process, ( https://prntscr.com/nuyzyd ) the progress
bar was long running and at the end it showed the following error (
https://prntscr.com/nuz039 ).

When I closed the popup and recaptured the FB account everything worked.

TKSSSSS




Em ter, 28 de mai de 2019 às 11:52, shue249 <notifications@github.com>
escreveu:

**Comment by shue249** [comment]
@svremeto We have another suggestion for you. Will you be able to access your MYSQL database and run the instructions on this comment? 
https://github.com/facebookincubator/Facebook-For-OpenCart/issues/177#issuecomment-495930585

**Comment by svremeto** [comment]
@shue249 Thanks. I receive this response http://prntscr.com/nvaznc

By the way, I remember something now. This website is a copy of my first website where facebook extension is installed and it's working properly most of the time.

**Comment by shue249** [comment]
@svremeto The information is helpful. You can try to run this command:

`SELECT * FROM oc_setting WHERE `code` = 'facebook';`

You should be seeing some rows that are returned. If this is correct, you can proceed to run this:

`DELETE FROM oc_setting WHERE `code` = 'facebook';`

**Comment by svremeto** [comment]
@shue249 Thank you very much! Everything is set now! The problem is resolved!

**Comment by shue249** [comment]
Thanks to all for the feedback. We will be closing out this ticket, feel free to reach to us if you have any further questions.

**Comment by svremeto** [comment]
@shue249 I`ve tried to upgrade the facebook extension of our old site as it was version 1. I`ve upgraded as its shown in the video but i was facing the same error as in the new website (which we already fixed it). 

So i replaced this file https://github.com/facebookincubator/Facebook-For-OpenCart/blob/master/upload/admin/controller/extension/facebookadsextension.php

After that i clicked Empty Cache and Hard Reload.

Nothing changed. After that i`ve tried this command as you advice:
delete from setting where code = 'facebook';

But received error https://prnt.sc/nvaznc 

and after that tried this command as you advice:
SELECT * FROM oc_setting WHERE code = 'facebook';
DELETE FROM oc_setting WHERE code = 'facebook';

After that clicked Admin/Modifications/Refresh and again Empty Cache and Hard Reload. 

After that i see this: http://prntscr.com/nw9to9

Could you please advice? Thank you!

**Comment by shue249** [comment]
@svremeto It seems that the "Get Started" button is missing. Can you open up javascript console and see if there are any errors when you access the Facebook Ads Extension module screen.

Also, can you help us to create a new ticket as this is a different issue.

**Comment by svremeto** [comment]
https://github.com/facebookincubator/Facebook-For-OpenCart/issues/186
