### ISSUE TITLE
use new version 2.1.10 the facebook Messenger not working

### ISSUE THREAD

**Issue by wegee-us** [facebookincubator/Facebook-For-OpenCart#188]
useing new version 2.1.10 the facebook Messenger not working, it's not showing front
![20190604003145](https://user-images.githubusercontent.com/50933832/58860077-2824e600-8660-11e9-837b-f2725911acdd.png)

**Comment by iq860** [comment]
same here :/
do u you have any edits done to the header in theme editor ?

**Comment by iq860** [comment]
i reverted back to 2.1.8 and messenger is back cuz 2.1.9 also was broke

**Comment by wegee-us** [comment]
actually the old version is ok, when i update to this version, it's disappeared

**Comment by shue249** [comment]
@wegee-us , @iq860 Thank you for the feedback. Yes, we made a change in version 2.1.9 to move the Messenger chat plugin from footer to header, so that opencart users can edit their footer.

1. Can you both install back the version 2.1.10 for us to verify on your store website what could be the problem.

2. As @iq860 mentioned, have you made any edits to the header theme? If you have made edits to header theme, then it is very likely that even the pixel firing is broken.

**Comment by iq860** [comment]
@shue249 
im back again on 2.1.10
no edits to the header 
oc 3.0.2.0
default theme

still no messenger

**Comment by shue249** [comment]
@iq860 We checked on your website and the messenger chat is loaded. (pls wait for a little while for the plugin to load) We also see that you are using 2.1.9, can you use 2.1.10 instead.

![image](https://user-images.githubusercontent.com/11957585/58898017-811b6b00-86ae-11e9-94f3-61db28d28695.png)

**Comment by iq860** [comment]
@shue249 
the website in speak is https://savona-me.com/
i have tried both 
2.1.9 and 2.1.10 and both no messenger 
now 2.1.10 is active

**Comment by iq860** [comment]
@shue249 
as an update clearing all cash and reinstalling the module several times its active again

**Comment by shue249** [comment]
@iq860 Sounds great! Which cache did you clear?

**Comment by iq860** [comment]
@shue249 
Theme & SASS

**Comment by shue249** [comment]
@wegee-us Can you try to also clear and disable the cache and let us know if it works.

**Comment by wegee-us** [comment]
@shue249 Hi, our website is high customized, even we clean the cache, it still not shows up again. but the old version is ok. so it should be some problem to add it to header. this is our website, you can take look.
wegee.us

**Comment by wegee-us** [comment]
and i did reinstall couple times, and also clean the setting from database. i think you should add an option to extension, then could let us choose where we can put the messager into

**Comment by shue249** [comment]
@wegee-us Have you used any plugins to compress/optimise the website?

**Comment by wegee-us** [comment]
yes, we do have this plugin: https://isenselabs.com/products/view/nitropack-complete-webstore-performance-optimization-framework?bgs=NitroPack

but the previous version has no problem. this new version is not working.

**Comment by wegee-us** [comment]
@shue249 hi, any solution for it? can you add an option to messager, then we can choose the plugin insert header or footer. my site may be only compatible for footer.

**Comment by shue249** [comment]
@wegee-us Let us look into how we can enable the messenger chat plugin on both header and footer to make it more robust for everyone.

**Comment by wegee-us** [comment]
@shue249 thanks

**Comment by wegee-us** [comment]
@shue249 Hi, any updates?

**Comment by shue249** [comment]
@wegee-us Apologies for the delay, we are working on some other fixes and will look into this asap and update you soonest.

**Comment by wegee-us** [comment]
@shue249 ok

**Comment by shue249** [comment]
@wegee-us  We have released a latest 2.1.11 version of the plugin which fixes this problem. 

Will be closing out this ticket. Feel free to reach to us if you have further questions.

**Comment by wegee-us** [comment]
@shue249 Hi, we updated to the Version: 2.1.12, the messenger is still not showing. and it shows an error, we already refresh the modification
![image](https://user-images.githubusercontent.com/50933832/66530133-5e192180-eabb-11e9-88b1-5c2d5c95e056.png)
