### ISSUE TITLE
Not complying with GDPR regulations because cookieconsent.js is using freegeoip API that is no longer available

### ISSUE THREAD

**Issue by amplexus** [facebookincubator/Facebook-For-OpenCart#19]
Hi,

I am getting lots of browser errors after installing this module.

The browser error I see is as follows:

```
cookieconsent.min.js:25 The service[0] (//freegeoip.net/json/?callback={callback}) responded with the following error Error: Error [UNKNOWN]: Invalid response (SyntaxError: Unexpected end of JSON input)
```

I clicked on the link to https://freegeoip.net/json/?callback=callback1532508093259 and can see that the API interface has been shut down:

```
{
  "0": "#################################################################################################################################",
  "1": "#                                                                                                                               #",
  "2": "# IMPORTANT - PLEASE UPDATE YOUR API ENDPOINT                                                                                   #",
  "3": "#                                                                                                                               #",
  "4": "# This API endpoint is deprecated and has now been shut down. To keep using the freegeoip API, please update your integration   #",
  "5": "# to use the new ipstack API endpoint, designed as a simple drop-in replacement.                                                #",
  "6": "# You will be required to create an account at https://ipstack.com and obtain an API access key.                                #",
  "7": "#                                                                                                                               #",
  "8": "# For more information on how to upgrade please visit our Github Tutorial at: https://github.com/apilayer/freegeoip#readme      #",
  "9": "#                                                                                                                               #",
  "a": "#################################################################################################################################"
}
```

Although these errors are not impacting my customers, it would be good to have this resolved so that my browser developer console is not cluttered with errors which makes it hard to detect and resolve genuine problems. 

Also, it would appear this error is preventing your module (and therefore my website) from complying with GDPR regulations.

Thanks,
Craig

![screenshot_20180727_072637](https://user-images.githubusercontent.com/9443081/43289499-8ab271ee-916e-11e8-9ebe-70cec7adb7ae.png)

**Comment by shue249** [comment]
Thanks for the feedback! We are looking into this now

**Comment by shue249** [comment]
Thank you for the feedback! We will work to put this into the next release and recognize your credit.

**Comment by shue249** [comment]
We have released the new version v2.0.3 which addressed this issue. We will be closing off this ticket, but feel free to open it if you have any further questions.

Facebook Ads Extension
Latest version: 2.0.3

Change log
2.0.3 - 7 August 2018
* Improves on the robustness of firing the Facebook pixels by using preactions (OpenCart v2.2.0.0 and higher) or tapping into the maintenance controller (lower than OpenCart v.2.2.0.0). This replaces almost all of the code-injection of Facebook pixel on the webstore front (files in catalog folder)
* Changes the pixel event Lead to Contact when users reach out to your store via the Contact Us form
* Added in a new pixel event, Subscribe, when users subscribe/unsubscribe to Newsletter
* Fixes the error for conflicting admin/controller/extension/module folder for OpenCart v2.0.3.1
* Fixes the console error for GDPR cookie consent due to outdated library files. Credits to Craig Jackson, @amplexus. https://github.com/facebookincubator/Facebook-For-OpenCart/issues/19
* Fixes a warning due to usage of the dirname command

**Comment by f1sh3rL** [comment]
Hi, ive installed the latest version but i am still getting the error? sorry to revive an old thread but it is driving me mad.

**Comment by shue249** [comment]
@f1sh3rL Can I ask for you to help us to create a new ticket here and share with us your website URL.
